root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
args_bin = []
bin = "./bin/server.exe"
cmd = "make build"
delay = 0
exclude_dir = [
    ".git",
    "assets",
    "internal/db",
    "bin",
    "tmp",
    "vendor",
    "testdata",
]
exclude_file = []
exclude_regex = ["_test\\.go"]
exclude_unchanged = false
follow_symlink = false
full_bin = ""
include_dir = []
include_ext = ["go", "tpl", "tmpl", "html"]
include_file = []
kill_delay = "0s"
log = "build-errors.log"
# Polling is used because currently WSL seems to have some issues with FSNotify
poll = true
poll_interval = 1000
post_cmd = []
pre_cmd = []
rerun = false
rerun_delay = 5000
send_interrupt = false
stop_on_error = false

[color]
app = ""
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
main_only = false
silent = false
time = true

[misc]
clean_on_exit = false

[proxy]
app_port = 3000
enabled = false
proxy_port = 0

[screen]
clear_on_rebuild = false
keep_scroll = true
