services:
  app:
    build:
      target: dev
    volumes:
      - .:/app
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 1GB
  caddy:
    ports:
      - 2019:2019
      - 80:80
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 2GB

  postgres:
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 1GB

  prometheus:
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 1GB
    # Grafana dashboards are preferred for actual monitoring and debugging, so this is only useful to confirm Caddy settings in dev.
    ports:
      - 9090:9090

  grafana:
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 1GB
  
