services:
  app:
    build:
      context: .
    container_name: zoubun-service
    environment:
      PORT: ${PORT}
      LOG_LEVEL: ${LOG_LEVEL}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    env_file:
      - ./.env
    depends_on:
      postgres:
        condition: service_healthy
    # Currently exposed for prometheus metrics
    # TODO: Remove without breaking prometheus metrics
    ports:
      - 3000:3000
    networks:
      - zoubun-network

  caddy:
    image: caddy
    container_name: zoubun-endpoint
    ports:
      - 80:80
    volumes:
      - caddy-config:/config
      - caddy-data:/data
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
    networks:
      - zoubun-network

  postgres:
    image: postgres:bookworm
    restart: always
    container_name: zoubun-db
    env_file:
      - ./.env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test:
        [CMD-SHELL, "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      - zoubun-network

  migrate:
    image: migrate/migrate
    container_name: zoubun-migrations
    env_file:
      - ./.env
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - zoubun-network
    volumes:
      - ./migrations/:/migrations
    command:
      [
        "-path",
        "/migrations",
        "-database",
        "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@zoubun-db/${POSTGRES_DB}?sslmode=disable",
        "up",
      ]

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml
      - prometheus_data:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yaml
      - --storage.tsdb.path=/prometheus
      - --web.console.libraries=/etc/prometheus/console_libraries
      - --web.console.templates=/etc/prometheus/consoles
      - --web.enable-lifecycle
    expose:
      - 9090
    ports:
      - 9090:9090
    networks:
      - zoubun-network

volumes:
  pg-data:
  caddy-config:
  caddy-data:
  prometheus_data:

networks:
  zoubun-network:
