global:
  scrape_interval: 15s
  scrape_failure_log_file: fail_prom.log
  query_log_file: query_prom.log


scrape_configs:
  - job_name: counters
    static_configs:
      - targets:
        - zoubun-service:3000

  - job_name: caddy
    static_configs:
      - targets: ["zoubun-endpoint"]
